server:
  port: 8080
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  format: TEXT

spring:
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
    dispatch-options-request: true

  kafka:
    bootstrap-servers: ${KAFKA_SERVER}
    properties:
      sasl:
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username='${KAFKA_USERNAME}' password='${KAFKA_PASSWORD}';
        mechanism: PLAIN
      security:
        protocol: SASL_SSL
    producer:
      client-id: sds-resolutions
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 2
    consumer:
      group-id: sds-resolutions
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      auto-offset-reset: earliest
    jaas:
      enabled: true

resolution:
  file: ${RESOLUTION_FILE}
